service: email-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"

functions:
  send-email:
    handler: handler.sendEmail
    url: true
