# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shami
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: email-service
service: email-service

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
